### ISSUE TITLE
arm64 builds

### ISSUE THREAD

**Issue by compiaffe** [Mihai-B/keycloak-arm#1]
@Mihai-B I've built an arm64 versions of keycloak: https://gitlab.com/aivero/public/keycloak-docker-arm64

Arm64 is actually fully supported by redhat, so no need to change anything. One can pull the container from:
```
docker pull registry.gitlab.com/aivero/public/keycloak-docker-arm64:12.0.1
```

> Note: There is no `latest` tag

**Comment by Mihai-B** [comment]
Hi @compiaffe . I didn't knew that redhat supports arm 64 by default, strange that they do not provide a keycloak image with arm64 support then.

I do have a question, you are building the image using the GitLab CI workers right? those are running on x86 cpu's if I am not mistaken

**Comment by compiaffe** [comment]
Hi @Mihai-B, yes I was surprised that there was a arm64 base image.

You are correct, the shared runners are x86. We have a Nvidia Jetson Xavier AGX hooked up as an arm64 runner since most of our company work requires builds for both x86 and arm64.

I did a quick test spinning the image on the xavier afterwards and it booted fine. That is the extent of the testing so far. 
But launching a x86 binary on arm arch throws some quite distinct errors.

**Comment by Mihai-B** [comment]
Ok, sound good. I can reference your image in the documentation, but can you add some documentation to your own repo? The hole reason why I created my own image is because even if there are other ARM images on docker hub, none of them provide any documentation and it is annoying from a user's perspective to guess what you have created there

**Comment by compiaffe** [comment]
@Mihai-B I've added a little bit of documentation: https://gitlab.com/aivero/public/keycloak-docker-arm64

I agree, on Docker Hub one cannot easily see what has been done or build. I've referenced our Gitlab CICD definition and one can see the logs of the jobs that produce the container. So I hope this makes it clear what I am doing here.
